export const teams = [
  {
    id: 1,
    name: 'HCCFrosh',
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'JO0F',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'StahpthecaP',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'MistyRaid',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'notEvoz',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Kimchi',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 2,
    name: 'buncha guys ere',
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'Bluelazer150',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'boxter',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Kino',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Nawkc',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Reference',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 3,
    name: 'The Mashed Potatoes',
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'Shotblast01',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'mb4wong',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'OGKigar',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'DWong03',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'ImFromSeason2',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 4,
    name: '(TSM) Team Servant (of Christ) Mid',
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'OmegaCherzerd',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Chmartin7',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'k0n9',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Ragingflare',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Wakande',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 5,
    name: 'Mac x UW CCF',
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'midbeastfan69',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Arthritis',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'tyco',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Soleil',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Gridlocx',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'flx',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 6,
    name: "Samson's Mullet",
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'Sequoia',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'bread',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Dr Schmeat',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'kilojoel',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Baxxer',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 7,
    name: 'Team 7',
    wins: 0,
    losses: 0,
    players: [
      {
        name: 'Jeffelini',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Cowvan',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'airade',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'destiger',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'cutebugst3r',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
];

export const games = [
  {
    key: '1',
    game: 'Round 1 Game 1',
    datetime: new Date(2020, 0, 2, 20, 0, 0).toDateString(),
    team1: 'HCCFrosh',
    team2: "Frank's Team",
    score: null,
    vod: 'https://www.twitch.tv/hoklaamc/',
  },
  {
    key: '2',
    game: 'Round 1 Game 2',
    datetime: new Date(2020, 11, 30, 21, 0, 0).toDateString(),
    team1: 'The Mashed Potatoes',
    team2: 'Team 7',
    score: null,
    vod: 'https://www.twitch.tv/hoklaamc/',
  },
  {
    key: '3',
    game: 'Round 1 Game 3',
    datetime: new Date(2021, 0, 2, 20, 0, 0).toDateString(),
    team1: 'Mac X UW CCF',
    team2: "Samson's Mullet",
    score: null,
    vod: 'https://www.twitch.tv/hoklaamc/',
  },
  {
    key: '4',
    game: 'Round 1 Game 4',
    datetime: new Date(2021, 0, 2, 21, 0, 0).toDateString(),
    team1: '(TSM) Team Servant (of Christ) Mid',
    team2: 'buncha guys ere',
    score: null,
    vod: 'https://www.twitch.tv/hoklaamc/',
  },
];
