export const teams = [
  {
    id: 1,
    name: 'HCCFrosh',
    gamesPlayed: 0,
    players: ['JO0F', 'Kimchi', 'MistyRaid', 'notEvoz', 'StahpthecaP'],
  },
  {
    id: 2,
    name: 'buncha guys ere',
    players: [
      'boxter',
      'Reference',
      'Bluelazer150',
      'Nawkc',
      'Kino',
      'SamFlanMan',
    ],
  },
  {
    id: 3,
    name: 'The Mashed Potatoes',
    gamesPlayed: 1,
    players: ['OGKigar', 'DWong03', 'Shotblast01', 'mb4wong', 'ImFromSeason2'],
  },
  {
    id: 4,
    name: '(TSM) Team Servant (of Christ) Mid',
    gamesPlayed: 2,
    players: [
      'Wakande',
      'k0n9',
      'chmartin7',
      'OmegaCherzerd',
      'Ragingflare',
      'Amanice Guy',
    ],
  },
  {
    id: 5,
    name: 'Mac x UW CCF',
    gamesPlayed: 0,
    players: [
      'tyco',
      'Arthritis',
      'MIDBEASTFAN69',
      'Soleil',
      'FLX',
      'Gridlocx',
    ],
  },
  {
    id: 6,
    name: "Samson's Mullet",
    gamesPlayed: 0,
    players: ['Sequoia', 'bread', 'gsong', 'kilojoel', 'Dr Schmeat', 'ttaiken'],
  },
  {
    id: 7,
    name: 'Team Iron + Daniel',
    players: ['Jeffelini', 'destiger', 'airade', 'cutebugst3r', 'Cowvan'],
  },
  {
    id: 8,
    name: 'iron chefs',
    gamesPlayed: 0,
    players: ['bran', 'Cyanine', 'yourgodname', 'AceHelosis', 'dragonsp'],
  },
];

export const games = [
  {
    key: '1',
    game: 'UB Round 1 Game 1',
    datetime: 'Wed Dec 30 2020 21:00 EST',
    team1: 'The Mashed Potatoes',
    team2: 'Team Iron + Daniel',
    maps: [
      {
        map: 'Split',
        team1Stats: [
          {
            key: '1',
            name: 'OGKigar',
            agent: 'reyna',
            acs: 376,
            kills: 20,
            deaths: 5,
            assists: 4,
            econ: 99,
          },
          {
            key: '2',
            name: 'DWong03',
            agent: 'raze',
            acs: 368,
            kills: 21,
            deaths: 6,
            assists: 6,
            econ: 125,
          },
          {
            key: '3',
            name: 'Shotblast01',
            agent: 'omen',
            acs: 231,
            kills: 13,
            deaths: 4,
            assists: 7,
            econ: 102,
          },
          {
            key: '4',
            name: 'mb4wong',
            agent: 'phoenix',
            acs: 221,
            kills: 12,
            deaths: 6,
            assists: 2,
            econ: 166,
          },
          {
            key: '5',
            name: 'ImFromSeason2',
            agent: 'breach',
            acs: 150,
            kills: 7,
            deaths: 8,
            assists: 7,
            econ: 59,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'Jeffelini',
            agent: 'brimstone',
            acs: 214,
            kills: 10,
            deaths: 15,
            assists: 2,
            econ: 90,
          },
          {
            key: '2',
            name: 'destiger',
            agent: 'jett',
            acs: 171,
            kills: 8,
            deaths: 14,
            assists: 3,
            econ: 40,
          },
          {
            key: '3',
            name: 'airade',
            agent: 'viper',
            acs: 148,
            kills: 7,
            deaths: 14,
            assists: 1,
            econ: 41,
          },
          {
            key: '4',
            name: 'cutebugst3r',
            agent: 'sage',
            acs: 60,
            kills: 2,
            deaths: 15,
            assists: 4,
            econ: 19,
          },
          {
            key: '5',
            name: 'Cowvan',
            agent: 'sova',
            acs: 50,
            kills: 2,
            deaths: 15,
            assists: 0,
            econ: 14,
          },
        ],
      },
    ],
    result: '13 - 2',
    vodId: '855925626',
    vodTime: '0h11m54s',
    vodLink: 'https://www.twitch.tv/videos/855925626?t=00h11m54s',
  },
  {
    key: '2',
    game: 'UB Round 1 Game 4',
    datetime: 'Sat Jan 2 2020 19:00 EST',
    team1: 'Mac x UW CCF',
    team2: "Samson's Mullet",
    maps: [
      {
        map: 'Split',
        team1Stats: [
          {
            key: '1',
            name: 'tyco',
            agent: 'raze',
            acs: 294,
            kills: 23,
            deaths: 15,
            assists: 5,
            econ: 62,
          },
          {
            key: '2',
            name: 'Arthritis',
            agent: 'viper',
            acs: 257,
            kills: 21,
            deaths: 14,
            assists: 1,
            econ: 65,
          },
          {
            key: '3',
            name: 'MIDBEASTFAN69',
            agent: 'breach',
            acs: 239,
            kills: 18,
            deaths: 15,
            assists: 9,
            econ: 48,
          },
          {
            key: '4',
            name: 'Soleil',
            agent: 'phoenix',
            acs: 197,
            kills: 14,
            deaths: 14,
            assists: 6,
            econ: 54,
          },
          {
            key: '5',
            name: 'FLX',
            agent: 'omen',
            acs: 148,
            kills: 11,
            deaths: 19,
            assists: 3,
            econ: 40,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'Sequoia',
            agent: 'jett',
            acs: 306,
            kills: 24,
            deaths: 16,
            assists: 5,
            econ: 72,
          },
          {
            key: '2',
            name: 'bread',
            agent: 'reyna',
            acs: 295,
            kills: 20,
            deaths: 18,
            assists: 7,
            econ: 70,
          },
          {
            key: '3',
            name: 'gsong',
            agent: 'omen',
            acs: 244,
            kills: 19,
            deaths: 18,
            assists: 4,
            econ: 63,
          },
          {
            key: '4',
            name: 'kilojoel',
            agent: 'phoenix',
            acs: 142,
            kills: 11,
            deaths: 18,
            assists: 5,
            econ: 34,
          },
          {
            key: '5',
            name: 'Dr Schmeat',
            agent: 'cypher',
            acs: 47,
            kills: 3,
            deaths: 17,
            assists: 3,
            econ: 15,
          },
        ],
      },
    ],
    result: '13-9',
    vodId: '859215462',
    vodTime: '0h8m21s',
    vodLink: 'https://www.twitch.tv/videos/859215462?t=0h8m21s',
  },
  {
    key: '3',
    game: 'UB Round 1 Game 2',
    datetime: 'Sat Jan 2 2020 20:00 EST',
    team1: '(TSM) Team Servant (of Christ) Mid',
    team2: 'buncha guys ere',
    maps: [
      {
        map: 'Haven',
        team1Stats: [
          {
            key: '1',
            name: 'Wakande',
            agent: 'jett',
            acs: 239,
            kills: 10,
            deaths: 12,
            assists: 1,
            econ: 57,
          },
          {
            key: '2',
            name: 'k0n9',
            agent: 'cypher',
            acs: 232,
            kills: 8,
            deaths: 13,
            assists: 5,
            econ: 58,
          },
          {
            key: '3',
            name: 'chmartin7',
            agent: 'phoenix',
            acs: 124,
            kills: 5,
            deaths: 13,
            assists: 1,
            econ: 27,
          },
          {
            key: '4',
            name: 'OmegaCherzerd',
            agent: 'omen',
            acs: 75,
            kills: 2,
            deaths: 13,
            assists: 1,
            econ: 26,
          },
          {
            key: '5',
            name: 'Amanice Guy',
            agent: 'sage',
            acs: 37,
            kills: 1,
            deaths: 13,
            assists: 1,
            econ: 11,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'boxter',
            agent: 'reyna',
            acs: 415,
            kills: 19,
            deaths: 5,
            assists: 4,
            econ: 102,
          },
          {
            key: '2',
            name: 'Reference',
            agent: 'jett',
            acs: 356,
            kills: 18,
            deaths: 7,
            assists: 3,
            econ: 72,
          },
          {
            key: '3',
            name: 'Bluelazer150',
            agent: 'omen',
            acs: 246,
            kills: 13,
            deaths: 6,
            assists: 2,
            econ: 94,
          },
          {
            key: '4',
            name: 'Nawkc',
            agent: 'killjoy',
            acs: 179,
            kills: 9,
            deaths: 5,
            assists: 2,
            econ: 46,
          },
          {
            key: '5',
            name: 'Kino',
            agent: 'sage',
            acs: 103,
            kills: 5,
            deaths: 3,
            assists: 6,
            econ: 44,
          },
        ],
      },
    ],
    result: '0-13',
    vodId: '859281321',
    vodTime: '0h17m6s',
    vodLink: 'https://www.twitch.tv/videos/859281321?t=0h17m6s',
  },
  {
    key: '4',
    game: 'UB Round 1 Game 3',
    datetime: 'Sat Jan 2 2020 21:00 EST',
    team1: 'HCCFrosh',
    team2: 'iron chefs',
    maps: [
      {
        map: 'Bind',
        team1Stats: [
          {
            key: '1',
            name: 'JO0F',
            agent: 'reyna',
            acs: 437,
            kills: 29,
            deaths: 7,
            assists: 3,
            econ: 124,
          },
          {
            key: '2',
            name: 'Kimchi',
            agent: 'killjoy',
            acs: 257,
            kills: 16,
            deaths: 9,
            assists: 4,
            econ: 78,
          },
          {
            key: '3',
            name: 'MistyRaid',
            agent: 'omen',
            acs: 198,
            kills: 13,
            deaths: 9,
            assists: 3,
            econ: 71,
          },
          {
            key: '4',
            name: 'notEvoz',
            agent: 'phoenix',
            acs: 197,
            kills: 11,
            deaths: 10,
            assists: 4,
            econ: 60,
          },
          {
            key: '5',
            name: 'StahpthecaP',
            agent: 'breach',
            acs: 110,
            kills: 7,
            deaths: 10,
            assists: 1,
            econ: 33,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'bran',
            agent: 'raze',
            acs: 434,
            kills: 26,
            deaths: 15,
            assists: 0,
            econ: 93,
          },
          {
            key: '2',
            name: 'Cyanine',
            agent: 'sova',
            acs: 170,
            kills: 8,
            deaths: 17,
            assists: 4,
            econ: 51,
          },
          {
            key: '3',
            name: 'yourgodname',
            agent: 'phoenix',
            acs: 138,
            kills: 6,
            deaths: 15,
            assists: 1,
            econ: 43,
          },
          {
            key: '4',
            name: 'AceHelosis',
            agent: 'omen',
            acs: 105,
            kills: 4,
            deaths: 15,
            assists: 6,
            econ: 26,
          },
          {
            key: '5',
            name: 'dragonsp',
            agent: 'sage',
            acs: 24,
            kills: 1,
            deaths: 14,
            assists: 5,
            econ: 6,
          },
        ],
      },
    ],
    result: '13-4',
    vodId: '859281321',
    vodTime: '1h12m45s',
    vodLink: 'https://www.twitch.tv/videos/859281321?t=1h12m45s',
  },
  {
    key: '5',
    game: 'LB Round 1 Game 2',
    datetime: 'Sun Jan 3 2020 20:00 EST',
    team1: 'iron chefs',
    team2: "Samson's Mullet",
    maps: [
      {
        map: 'Bind',
        team1Stats: [
          {
            key: '1',
            name: 'bran',
            agent: 'raze',
            acs: 326,
            kills: 22,
            deaths: 16,
            assists: 3,
            econ: 83,
          },
          {
            key: '2',
            name: 'yourgodname',
            agent: 'phoenix',
            acs: 208,
            kills: 14,
            deaths: 17,
            assists: 3,
            econ: 83,
          },
          {
            key: '3',
            name: 'AceHelosis',
            agent: 'cypher',
            acs: 179,
            kills: 11,
            deaths: 18,
            assists: 4,
            econ: 37,
          },
          {
            key: '4',
            name: 'Cyanine',
            agent: 'omen',
            acs: 140,
            kills: 9,
            deaths: 18,
            assists: 3,
            econ: 30,
          },
          {
            key: '5',
            name: 'dragonsp',
            agent: 'sage',
            acs: 56,
            kills: 3,
            deaths: 18,
            assists: 2,
            econ: 20,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'ttaiken',
            agent: 'jett',
            acs: 511,
            kills: 36,
            deaths: 12,
            assists: 4,
            econ: 123,
          },
          {
            key: '2',
            name: 'bread',
            agent: 'reyna',
            acs: 233,
            kills: 17,
            deaths: 10,
            assists: 4,
            econ: 69,
          },
          {
            key: '3',
            name: 'kilojoel',
            agent: 'phoenix',
            acs: 228,
            kills: 16,
            deaths: 14,
            assists: 9,
            econ: 55,
          },
          {
            key: '4',
            name: 'gsong',
            agent: 'omen',
            acs: 132,
            kills: 10,
            deaths: 12,
            assists: 3,
            econ: 43,
          },
          {
            key: '5',
            name: 'Sequoia',
            agent: 'sage',
            acs: 102,
            kills: 8,
            deaths: 11,
            assists: 8,
            econ: 30,
          },
        ],
      },
    ],
    result: '7 - 13',
    vodId: '860482503',
    vodTime: '0h17m48s',
    vodLink: 'https://www.twitch.tv/videos/860482503?t=0h17m48s',
  },
  {
    key: '6',
    game: 'LB Round 1 Game 1',
    datetime: 'Sun Jan 3 2020 21:00 EST',
    team1: 'Team Iron + Daniel',
    team2: '(TSM) Team Servant (of Christ) Mid',
    maps: [
      {
        map: 'Bind',
        // team1Stats: [{
        //   key: '1',
        //   name: 'Jeffelini',
        //   agent: 'brimstone',
        //   acs: 214,
        //   kills: 10,
        //   deaths: 15,
        //   assists: 2,
        //   econ: 90,
        // },
        // {
        //   key: '2',
        //   name: 'destiger',
        //   agent: 'jett',
        //   acs: 171,
        //   kills: 8,
        //   deaths: 14,
        //   assists: 3,
        //   econ: 40,
        // },
        // {
        //   key: '3',
        //   name: 'airade',
        //   agent: 'viper',
        //   acs: 148,
        //   kills: 7,
        //   deaths: 14,
        //   assists: 1,
        //   econ: 41,
        // },
        // {
        //   key: '4',
        //   name: 'cutebugst3r',
        //   agent: 'sage',
        //   acs: 60,
        //   kills: 2,
        //   deaths: 15,
        //   assists: 4,
        //   econ: 19,
        // },
        // {
        //   key: '5',
        //   name: 'Cowvan',
        //   agent: 'sova',
        //   acs: 50,
        //   kills: 2,
        //   deaths: 15,
        //   assists: 0,
        //   econ: 14,
        // },],
        // team2Stats: [
        //   {
        //     key: '1',
        //     name: 'Wakande',
        //     agent: 'jett',
        //     acs: 239,
        //     kills: 10,
        //     deaths: 12,
        //     assists: 1,
        //     econ: 57,
        //   },
        //   {
        //     key: '2',
        //     name: 'k0n9',
        //     agent: 'cypher',
        //     acs: 232,
        //     kills: 8,
        //     deaths: 13,
        //     assists: 5,
        //     econ: 58,
        //   },
        //   {
        //     key: '3',
        //     name: 'chmartin7',
        //     agent: 'phoenix',
        //     acs: 124,
        //     kills: 5,
        //     deaths: 13,
        //     assists: 1,
        //     econ: 27,
        //   },
        //   {
        //     key: '4',
        //     name: 'OmegaCherzerd',
        //     agent: 'omen',
        //     acs: 75,
        //     kills: 2,
        //     deaths: 13,
        //     assists: 1,
        //     econ: 26,
        //   },
        //   {
        //     key: '5',
        //     name: 'TBD',
        //     agent: 'sage',
        //     acs: 37,
        //     kills: 1,
        //     deaths: 13,
        //     assists: 1,
        //     econ: 11,
        //   },
        // ],
      },
    ],
    result: '1 - 13',
    vodId: '860560840',
    vodTime: '0h5m32s',
    vodLink: 'https://www.twitch.tv/videos/860560840?t=0h5m32s',
  },
  {
    key: '7',
    game: 'UB Round 2 Game 2',
    datetime: 'Mon Jan 4 2020 20:00 EST',
    team1: 'HCCFrosh',
    team2: 'Mac x UW CCF',
    maps: [
      {
        map: 'Ascent',
        team1Stats: [
          {
            key: '1',
            name: 'JO0F',
            agent: 'reyna',
            acs: 327,
            kills: 26,
            deaths: 13,
            assists: 7,
            econ: 108,
          },
          {
            key: '2',
            name: 'MistyRaid',
            agent: 'omen',
            acs: 270,
            kills: 19,
            deaths: 18,
            assists: 9,
            econ: 58,
          },
          {
            key: '3',
            name: 'Kimchi',
            agent: 'killjoy',
            acs: 245,
            kills: 16,
            deaths: 14,
            assists: 8,
            econ: 66,
          },
          {
            key: '4',
            name: 'StahpthecaP',
            agent: 'breach',
            acs: 132,
            kills: 9,
            deaths: 16,
            assists: 9,
            econ: 34,
          },
          {
            key: '5',
            name: 'notEvoz',
            agent: 'sova',
            acs: 103,
            kills: 7,
            deaths: 16,
            assists: 3,
            econ: 28,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'tyco',
            acs: 261,
            kills: 17,
            deaths: 18,
            assists: 9,
            econ: 64,
          },
          {
            key: '2',
            name: 'Gridlocx',
            acs: 242,
            kills: 19,
            deaths: 17,
            assists: 6,
            econ: 64,
          },
          {
            key: '3',
            name: 'Soleil',
            acs: 223,
            kills: 17,
            deaths: 13,
            assists: 7,
            econ: 88,
          },
          {
            key: '4',
            name: 'MIDBEASTFAN69',
            acs: 170,
            kills: 11,
            deaths: 16,
            assists: 9,
            econ: 47,
          },
          {
            key: '5',
            name: 'Arthritis',
            acs: 163,
            kills: 13,
            deaths: 13,
            assists: 8,
            econ: 35,
          },
        ],
      },
    ],
    result: '9 - 13',
    vodId: '861632326',
    vodTime: '0h15m18s',
    vodLink: 'https://www.twitch.tv/videos/861632326?t=0h15m18s',
  },
  {
    key: '8',
    game: 'UB Round 2 Game 1',
    datetime: 'Mon Jan 4 2020 21:00 EST',
    team1: 'The Mashed Potatoes',
    team2: 'buncha guys ere',
    maps: [
      {
        map: 'Bind',
        team1Stats: [
          {
            key: '1',
            name: 'DWong03',
            agent: 'raze',
            acs: 331,
            kills: 27,
            deaths: 22,
            assists: 6,
            econ: 71,
          },
          {
            key: '2',
            name: 'OGKigar',
            agent: 'reyna',
            acs: 308,
            kills: 27,
            deaths: 17,
            assists: 7,
            econ: 88,
          },
          {
            key: '3',
            name: 'Shotblast01',
            agent: 'omen',
            acs: 189,
            kills: 17,
            deaths: 17,
            assists: 4,
            econ: 60,
          },
          {
            key: '4',
            name: 'ImFromSeason2',
            agent: 'killjoy',
            acs: 162,
            kills: 14,
            deaths: 16,
            assists: 4,
            econ: 59,
          },
          {
            key: '5',
            name: 'mb4wong',
            agent: 'phoenix',
            acs: 142,
            kills: 1,
            deaths: 19,
            assists: 4,
            econ: 31,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'boxter',
            agent: 'sova',
            acs: 318,
            kills: 30,
            deaths: 18,
            assists: 5,
            econ: 79,
          },
          {
            key: '2',
            name: 'SamFlanMan',
            agent: 'reyna',
            acs: 265,
            kills: 22,
            deaths: 20,
            assists: 6,
            econ: 71,
          },
          {
            key: '3',
            name: 'Bluelazer150',
            agent: 'omen',
            acs: 240,
            kills: 22,
            deaths: 19,
            assists: 4,
            econ: 56,
          },
          {
            key: '4',
            name: 'Reference',
            agent: 'jett',
            acs: 201,
            kills: 15,
            deaths: 17,
            assists: 8,
            econ: 58,
          },
          {
            key: '5',
            name: 'Kino',
            agent: 'sage',
            acs: 60,
            kills: 2,
            deaths: 22,
            assists: 8,
            econ: 18,
          },
        ],
      },
    ],
    result: '12 - 14',
    vodId: '861720936',
    vodTime: '0h10m52s',
    vodLink: 'https://www.twitch.tv/videos/861720936?t=0h10m52s',
  },
  {
    key: '9',
    game: 'LB Round 2 Game 1',
    datetime: 'Tue Jan 5 2020 20:00 EST',
    team1: '(TSM) Team Servant (of Christ) Mid',
    team2: 'HCCFrosh',
    maps: [
      {
        map: 'split',
        team1Stats: [
          {
            key: '1',
            name: 'k0n9',
            agent: 'raze',
            acs: 192,
            kills: 9,
            deaths: 16,
            assists: 3,
            econ: 46,
          },
          {
            key: '2',
            name: 'Doritz',
            agent: 'killjoy',
            acs: 184,
            kills: 7,
            deaths: 15,
            assists: 2,
            econ: 44,
          },
          {
            key: '3',
            name: 'chmartin7',
            agent: 'phoenix',
            acs: 171,
            kills: 9,
            deaths: 15,
            assists: 4,
            econ: 40,
          },
          {
            key: '4',
            name: 'Wakande',
            agent: 'jett',
            acs: 165,
            kills: 8,
            deaths: 15,
            assists: 3,
            econ: 40,
          },
          {
            key: '5',
            name: 'OmegaCherzerd',
            agent: 'omen',
            acs: 124,
            kills: 7,
            deaths: 14,
            assists: 1,
            econ: 36,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'JO0F',
            agent: 'reyna',
            acs: 400,
            kills: 23,
            deaths: 9,
            assists: 7,
            econ: 136,
          },
          {
            key: '2',
            name: 'notEvoz',
            agent: 'phoenix',
            acs: 388,
            kills: 25,
            deaths: 7,
            assists: 3,
            econ: 109,
          },
          {
            key: '3',
            name: 'Kimchi',
            agent: 'sage',
            acs: 238,
            kills: 13,
            deaths: 8,
            assists: 5,
            econ: 44,
          },
          {
            key: '4',
            name: 'MistyRaid',
            agent: 'omen',
            acs: 180,
            kills: 10,
            deaths: 8,
            assists: 4,
            econ: 83,
          },
          {
            key: '5',
            name: 'StahpthecaP',
            agent: 'breach',
            acs: 73,
            kills: 4,
            deaths: 8,
            assists: 7,
            econ: 25,
          },
        ],
      },
    ],
    result: '3 - 13',
    vodId: '862832156',
    vodTime: '0h17m34s',
    vodLink: 'https://www.twitch.tv/videos/862832156?t=0h17m34s',
  },
  {
    key: '10',
    game: 'LB Round 2 Game 2',
    datetime: 'Tue Jan 5 2020 21:00 EST',
    team1: "Samson's Mullet",
    team2: 'buncha guys ere',
    maps: [
      {
        map: 'Ascent',
        team1stats: [
          {
            key: '1',
            name: 'gsong',
            agent: 'omen',
            acs: 421,
            kills: 22,
            deaths: 6,
            assists: 5,
            econ: 97,
          },
          {
            key: '2',
            name: 'Sequoia',
            agent: 'jett',
            acs: 362,
            kills: 21,
            deaths: 7,
            assists: 2,
            econ: 65,
          },
          {
            key: '3',
            name: 'kilojoel',
            agent: 'phoenix',
            acs: 264,
            kills: 12,
            deaths: 7,
            assists: 10,
            econ: 70,
          },
          {
            key: '4',
            name: 'bread',
            agent: 'sage',
            acs: 188,
            kills: 10,
            deaths: 6,
            assists: 9,
            econ: 67,
          },
          {
            key: '5',
            name: 'Heffren Lo',
            agent: 'sova',
            acs: 106,
            kills: 4,
            deaths: 5,
            assists: 6,
            econ: 47,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'Reference',
            agent: 'jett',
            acs: 244,
            kills: 10,
            deaths: 14,
            assists: 0,
            econ: 62,
          },
          {
            key: '2',
            name: 'SamFlanMan',
            agent: 'reyna',
            acs: 214,
            kills: 9,
            deaths: 14,
            assists: 3,
            econ: 61,
          },
          {
            key: '3',
            name: 'boxter',
            agent: 'sova',
            acs: 185,
            kills: 7,
            deaths: 13,
            assists: 1,
            econ: 72,
          },
          {
            key: '4',
            name: 'Bluelazer150',
            agent: 'omen',
            acs: 86,
            kills: 3,
            deaths: 14,
            assists: 2,
            econ: 24,
          },
          {
            key: '5',
            name: 'Nawkc',
            agent: 'sage',
            acs: 47,
            kills: 2,
            deaths: 14,
            assists: 6,
            econ: 9,
          },
        ],
      },
    ],
    result: '13 - 1',
    vodId: '862897070',
    vodTime: '0h23m52s',
    vodLink: 'https://www.twitch.tv/videos/862897070?t=0h23m52s',
  },
  {
    key: '11',
    game: 'LB Round 3',
    datetime: 'Wed Jan 6 2020 21:00 EST',
    team1: 'HCCFrosh',
    team2: "Samson's Mullet",
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
  },
  {
    key: '12',
    game: 'UB Finals',
    datetime: 'Thu Jan 7 2020 21:00 EST',
    team1: 'The Mashed Potatoes',
    team2: 'Mac x UW CCF',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
  },
  {
    key: '13',
    game: 'LB Finals',
    datetime: 'Fri Jan 8 2020 21:00 EST',
    team1: 'Winner of LB Round 3',
    team2: 'Loser of UB Finals',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
  },
  {
    key: '14',
    game: 'Grand Finals',
    datetime: 'Sat Jan 9 2020 20:00 EST',
    team1: 'Winner of UB Finals',
    team2: 'Winner of LB Finals',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
  },
];
