export const teams = [
  {
    id: 1,
    name: 'HCCFrosh',
    gamesPlayed: 0,
    players: [
      {
        name: 'JO0F',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'StahpthecaP',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'MistyRaid',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'notEvoz',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Kimchi',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 2,
    name: 'buncha guys ere',
    gamesPlayed: 0,
    players: [
      {
        name: 'Bluelazer150',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'boxter',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Kino',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Nawkc',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Reference',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 3,
    name: 'The Mashed Potatoes',
    gamesPlayed: 1,
    players: [
      {
        name: 'OGKigar',
        acs: 376,
        kills: 20,
        deaths: 5,
        assists: 4,
        econ: 99,
      },
      {
        name: 'DWong03',
        acs: 368,
        kills: 21,
        deaths: 6,
        assists: 6,
        econ: 125,
      },
      {
        name: 'Shotblast01',
        acs: 231,
        kills: 13,
        deaths: 4,
        assists: 7,
        econ: 102,
      },
      {
        name: 'mb4wong',
        acs: 221,
        kills: 12,
        deaths: 6,
        assists: 2,
        econ: 166,
      },
      {
        name: 'ImFromSeason2',
        acs: 150,
        kills: 7,
        deaths: 8,
        assists: 7,
        econ: 59,
      },
    ],
  },
  {
    id: 4,
    name: '(TSM) Team Servant (of Christ) Mid',
    gamesPlayed: 0,
    players: [
      {
        name: 'OmegaCherzerd',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Chmartin7',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'k0n9',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Ragingflare',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Wakande',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 5,
    name: 'Mac x UW CCF',
    gamesPlayed: 0,
    players: [
      {
        name: 'midbeastfan69',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Arthritis',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'tyco',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Soleil',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Gridlocx',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'flx',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 6,
    name: "Samson's Mullet",
    gamesPlayed: 0,
    players: [
      {
        name: 'Sequoia',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'bread',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Dr Schmeat',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'kilojoel',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'Baxxer',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
  {
    id: 7,
    name: 'Team Iron + Daniel',
    gamesPlayed: 1,
    players: [
      {
        name: 'Jeffelini',
        acs: 214,
        kills: 10,
        deaths: 15,
        assists: 2,
        econ: 90,
      },
      {
        name: 'destiger',
        acs: 171,
        kills: 8,
        deaths: 14,
        assists: 3,
        econ: 40,
      },
      {
        name: 'airade',
        acs: 148,
        kills: 7,
        deaths: 14,
        assists: 1,
        econ: 41,
      },
      {
        name: 'cutebugst3r',
        acs: 60,
        kills: 2,
        deaths: 15,
        assists: 4,
        econ: 19,
      },
      {
        name: 'Cowvan',
        acs: 50,
        kills: 2,
        deaths: 15,
        assists: 0,
        econ: 14,
      },
    ],
  },
  {
    id: 8,
    name: 'iron chefs',
    gamesPlayed: 0,
    players: [
      {
        name: 'Cyanine',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'AceHelosis',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'yourgodname',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'dragonsp',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
      {
        name: 'bran',
        acs: 0,
        kills: 0,
        deaths: 0,
        assists: 0,
        econ: 0,
      },
    ],
  },
];

export const games = [
  {
    key: '1',
    game: 'UB Round 1 Game 1',
    datetime: 'Wed Dec 30 2020 21:00 EST',
    team1: 'The Mashed Potatoes',
    team2: 'Team Iron + Daniel',
    maps: [
      {
        map: 'Split',
        team1Stats: [
          {
            key: '1',
            name: 'OGKigar',
            acs: 376,
            kills: 20,
            deaths: 5,
            assists: 4,
            econ: 99,
          },
          {
            key: '2',
            name: 'DWong03',
            acs: 368,
            kills: 21,
            deaths: 6,
            assists: 6,
            econ: 125,
          },
          {
            key: '3',
            name: 'Shotblast01',
            acs: 231,
            kills: 13,
            deaths: 4,
            assists: 7,
            econ: 102,
          },
          {
            key: '4',
            name: 'mb4wong',
            acs: 221,
            kills: 12,
            deaths: 6,
            assists: 2,
            econ: 166,
          },
          {
            key: '5',
            name: 'ImFromSeason2',
            acs: 150,
            kills: 7,
            deaths: 8,
            assists: 7,
            econ: 59,
          },
        ],
        team2Stats: [
          {
            key: '1',
            name: 'Jeffelini',
            acs: 214,
            kills: 10,
            deaths: 15,
            assists: 2,
            econ: 90,
          },
          {
            key: '2',
            name: 'destiger',
            acs: 171,
            kills: 8,
            deaths: 14,
            assists: 3,
            econ: 40,
          },
          {
            key: '3',
            name: 'airade',
            acs: 148,
            kills: 7,
            deaths: 14,
            assists: 1,
            econ: 41,
          },
          {
            key: '4',
            name: 'cutebugst3r',
            acs: 60,
            kills: 2,
            deaths: 15,
            assists: 4,
            econ: 19,
          },
          {
            key: '5',
            name: 'Cowvan',
            acs: 50,
            kills: 2,
            deaths: 15,
            assists: 0,
            econ: 14,
          },
        ],
      },
    ],
    result: '13 - 2',
    vodId: '855925626',
    vodIdTime: '0h11m54s',
    vodLink: 'https://www.twitch.tv/videos/855925626?t=00h11m54s',
    tentative: false,
  },
  {
    key: '2',
    game: 'UB Round 1 Game 4',
    datetime: 'Sat Jan 2 2020 19:00 EST',
    team1: 'Mac X UW CCF',
    team2: "Samson's Mullet",
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: false,
  },
  {
    key: '3',
    game: 'UB Round 1 Game 3',
    datetime: 'Sat Jan 2 2020 20:00 EST',
    team1: 'HCCFrosh',
    team2: 'iron chefs',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: false,
  },

  {
    key: '4',
    game: 'UB Round 1 Game 2',
    datetime: 'Sat Jan 2 2020 21:00 EST',
    team1: '(TSM) Team Servant (of Christ) Mid',
    team2: 'buncha guys ere',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: false,
  },
  {
    key: '5',
    game: 'LB Round 1 Game 1',
    datetime: 'Sun Jan 3 2020 20:00 EST',
    team1: 'Loser of UB Round 1 Game 1',
    team2: 'Loser of UB Round 1 Game 2',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '6',
    game: 'LB Round 1 Game 2',
    datetime: 'Sun Jan 3 2020 21:00 EST',
    team1: 'Loser of UB Round 1 Game 3',
    team2: 'Loser of UB Round 1 Game 4',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '7',
    game: 'UB Round 2 Game 1',
    datetime: 'Mon Jan 4 2020 20:00 EST',
    team1: 'Winner of UB Round 1 Game 1',
    team2: 'Winner of UB Round 1 Game 2',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '8',
    game: 'UB Round 2 Game 2',
    datetime: 'Mon Jan 4 2020 21:00 EST',
    team1: 'Winner of UB Round 1 Game 3',
    team2: 'Winner of UB Round 1 Game 4',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '9',
    game: 'LB Round 2 Game 1',
    datetime: 'Tue Jan 5 2020 20:00 EST',
    team1: 'Winner of LB Round 1 Game 1',
    team2: 'Loser of UB Round 2 Game 2',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '10',
    game: 'LB Round 2 Game 2',
    datetime: 'Tue Jan 5 2020 21:00 EST',
    team1: 'Winner of LB Round 1 Game 2',
    team2: 'Loser of UB Round 2 Game 1',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '11',
    game: 'LB Round 3',
    datetime: 'Wed Jan 6 2020 21:00 EST',
    team1: 'Winner of LB Round 2 Game 1',
    team2: 'Winner of LB Round 2 Game 2',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '12',
    game: 'UB Finals',
    datetime: 'Thu Jan 7 2020 21:00 EST',
    team1: 'Winner of UB Round 2 Game 1',
    team2: 'Winner of UB Round 2 Game 2',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '13',
    game: 'LB Finals',
    datetime: 'Fri Jan 8 2020 21:00 EST',
    team1: 'Winner of LB Round 3',
    team2: 'Loser of UB Finals',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
  {
    key: '14',
    game: 'Grand Finals',
    datetime: 'Sat Jan 9 2020 20:00 EST',
    team1: 'Winner of UB Finals',
    team2: 'Winner of LB Finals',
    maps: [],
    result: null,
    vodLink: 'https://www.twitch.tv/hoklaamc/',
    tentative: true,
  },
];
